databases:
  - name: activate-ghana-db
    databaseName: activate_ghana
    user: activate_ghana

services:
  - type: web
    name: activate-ghana-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn skillset.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://activate-ghana.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://activate-ghana.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: activate-ghana-db
          property: connectionString

  - type: static
    name: activate-ghana-web
    staticPublishPath: .
    buildCommand: "npm install && npm run build:css"
